services:
  users-server:
    build: users
    image: users-server
    container_name: users-server
    ports:
      - "9090:9090"
    depends_on:
      - users-db

  users-db:
    image: postgres:16.1
    container_name: users-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=users
      - POSTGRES_USER=users
      - POSTGRES_DB=users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10