services:
  gateway:
    build: gateway
    image: gateway-server
    container_name: gateway-server
    ports:
      - "8085:8085"
    depends_on:
      - users-server
      - companies-server

  users-server:
    build: users
    image: users-server
    container_name: users-server
    ports:
      - "9090:9090"
    depends_on:
      - users-db

  users-db:
    image: postgres:16.1
    container_name: users-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=users
      - POSTGRES_USER=users
      - POSTGRES_DB=users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  companies-server:
    build: companies
    image: companies-server
    container_name: companies-server
    ports:
      - "8080:8080"
    depends_on:
      - companies-db

  companies-db:
    image: postgres:16.1
    container_name: companies-db
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_PASSWORD=companies
      - POSTGRES_USER=companies
      - POSTGRES_DB=companies
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10