server:
  port: 9090

companies:
  url: http://companies-server:8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://users-db:5432/users
    username: users
    password: users
  jpa:
    properties:
      hibernate:
        show_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
