server:
  port: 8085

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://users-server:9090
          predicates:
            - Path=/users/**
        - id: companies-service
          uri: http://companies-server:8080
          predicates:
            - Path=/companies/**