server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://users
          predicates:
            - Path=/users/**
        - id: companies-service
          uri: lb://companies
          predicates:
            - Path=/companies/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka