server:
  port: 8080

users:
  url: http://users-server:9090

spring:
  application:
    name: companies
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://companies-db:5432/companies
    username: companies
    password: companies
  jpa:
    properties:
      hibernate:
        show_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka