server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://companies-db:5432/companies
    username: companies
    password: companies
  jpa:
    properties:
      hibernate:
        show_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: DEBUG
